### ISSUE TITLE
Correct way to import cordova.js

### ISSUE THREAD

**Issue by PedroBorracho** [orchoban/react.cordova#10]
Hi,

looking in to Cordova documentation, the access to the plugins is done via 
`
cordova.plugins.<...>
`

But with react.cordova which is the best way to include the cordava.js file? The index.html generated by the build can be edited? Cordova should be imported as npm dependency in any js file of the app that will use a plugin?

Thanks for the help!

**Comment by orchoban** [comment]
What is the plugin you use?

**Comment by PedroBorracho** [comment]
I'm trying both standard plugin
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-device/index.html

and custom plugins
https://github.com/phonegap/phonegap-plugin-barcodescanner

In the the project created with the cli, I don't see the JS files of Cordova being loaded by the webview: are they part of the Webpack bundle? Do you have an example of how to use any plugin/cordova API?

I had also to add to the package.json the field homepage to make the app boot
`
"homepage": "."
`
because the content under "/static" was not loaded correctly iOs Simulator

**Comment by orchoban** [comment]
Get the first plugin with `window.device.cordova`
The second `window.cordova.plugins.barcodeScanner.scan`

Each plugin explain in the tutorial how to get the interface within the `window`.

**Comment by PedroBorracho** [comment]
thanks, it's clear to me how cordova and plugins should work, my question is more on how reco is loading/packaging the JS part of cordova within the application.

Creating a new project with the cli
`reco init com.rgonella.testreco "testreco"`

the JS scripts of cordova are not loaded in page:

- I don't see it loaded in page or packaged in the bundle because both window.cordova
<img width="747" alt="Screenshot 2020-01-13 at 08 22 34" src="https://user-images.githubusercontent.com/1810992/72240327-12a76f80-35e4-11ea-9892-44aaf585caa4.png">
- it's included in the bundle because _window.device_ and _window.cordova_ are both undefined.

On more thing the I don't see in the created project is the listener on _deviceready_, the event fired by cordova when successfully connected to the device.

Do you have a example of dealing with Cordova js APIs?

**Comment by orchoban** [comment]
Can you upload the project you created to github? 
I'll check it out for you.

**Comment by orchoban** [comment]
@arkwld

**Comment by arkwld** [comment]
Dear @PedroBorracho 

I ran an application based on react.cordova on an iPhone 8 simulator. The application launched and all the resources loaded successfully. Yet, opened the "Web Inspector" (as you did) and saw that "cordova.js" failed to load (see screenshot attached). However, checked the error and seems that the failure occured as a result of an attempt to load the "cordova.js" script from the "browser" platform. This issue needs to be further explored, but it seems to me (and I may be wrong) that the "cordova.js" resource did load successfully from the "ios" platform since cordova+plugins are functional. I agree that when dealing with either iOS/Android platforms it is possible that cordova.js is compiled as part of the Webpack, hence you do not see an actual request coming from WebView to load it (We need to further check this issue). Hope this somewhat clarifies the important issue that you raised. We will definitely look into it more extenssively and will provide you with futher feedback

Best wishes to you

<img width="1043" alt="screenshot" src="https://user-images.githubusercontent.com/54232849/72337599-85d7e100-36cb-11ea-8f6d-9d6a028d89fa.png">

**Comment by arkwld** [comment]
@PedroBorracho 

Went over the web inspector again an saw that "cordova.js" and "cordova_plugins.js" were loaded successfully. Cordova.js loaded successfully from the following device simulator path:

file:///Users/macuser/Library/Developer/CoreSimulator/Devices/D8A27F7C-4407-41D9-8E8B-ACC3D4C806AE/data/Containers/Bundle/Application/FB1C829A-6910-4A22-95D5-415E62380983/%D7%A8%D7%93%D7%99%D7%95%20%D7%9E%D7%94%D7%95%D7%AA%20%D7%94%D7%97%D7%99%D7%99%D7%9D.app/www/cordova.js

So as you see now, "cordova.js" is not part of the Webpack (which is mainly related to the reactjs compiled code) and is loaded independently as in any Cordova based application. Hence, the WebView in any platform, loads it independently. It is possible that your test application has encountered some other error or exception that prevented the cordova.js script from loading

**Comment by PedroBorracho** [comment]
Hi,

I uploaded the project created with the CLI here:
https://github.com/PedroBorracho/testreco

Thanks for the help on debugging the issue, I did not see any error in console using Safari Inspector

**Comment by rudicus** [comment]
@PedroBorracho - I noticed if I run cordova serve manually, it hosts the cordova.js file automatically.

**Comment by huangyanxiong01** [comment]
The same to you. Can you tell me resolved it
